name: "🔌 Github CI - Actions"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: 🦀 Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🛡️ Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: 📁 Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🛠️ Set up Go toolchain
        uses: actions/setup-go@v6.5.0
        with:
          go-version: "1.26.1"
          cache-dependency-path: "**/go.sum"

      - name: 🔍 Go vet
        run: |
          for dir in ci-status fix-notifier label-pr-issue release-notes unreleased-commits versions-dropdown; do
            go vet ./${dir}/...
          done

      - name: 🧪 Run tests
        run: |
          for dir in ci-status fix-notifier label-pr-issue release-notes unreleased-commits versions-dropdown; do
            go test ./${dir}/...
          done

  check-spell:
    name: 📝 Check spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🛡️ Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: 📁 Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 📝 Check spelling
        uses: crate-ci/typos@7b04f660f4ee4f048d18fd341887cf28dfbedfe2 # v1.46.3
